(function(){function r(e,c){var d;e.some(function(b,a){if(c>b.end_normalized)return!1;d=b;return!0});return d?d:e[0]}function s(e,c){for(var d=!1,b=0;b<g.length;b++)for(var a=0;a<g[b].dom_elements.length;a++)g[b].start.day()===e?(g[b].dom_elements[a].style.color="#333",d=!0):g[b].dom_elements[a].style.color="grey";if(!d)for(d=c.start.day(),b=0;b<g.length;b++)if(g[b].start.day()===d)for(a=0;a<g[b].dom_elements.length;a++)g[b].dom_elements[a].style.color="#333"}function n(){var e=moment(),c=e.unix(),
d=c-e.clone().startOf("isoWeek").unix(),b=c-e.clone().startOf("day").unix(),c=e.day();c!==t&&s(c,h);t=c;e=e.hour()-Math.floor(b/3600);d+=3600*e;if(h.is_live(d))return m=!0,u(!0);if(m)return m=!1,h=r(g,d),s(c,h),n();m=!1;return u(!1,v(d,h.start_normalized))}var w=moment().tz("america/vancouver").isDST(),q=(new Date).getTimezoneOffset(),g=function(){function e(a,c,d){if(!(this instanceof e))return new e(a,c,d);this.start=c;a=a.toLowerCase();a=b.indexOf(a);if(-1===a)throw Error("Invalid weekday name");
this.isoWeekday=a+1;this.duration=d}function c(a,b){if(!(this instanceof c))return new c(a,b);this.start=a.clone().zone(q);this.end=a.clone().zone(q);this.end.add("hours",b);this.duration=b;this.start_normalized=this.start.unix()-this.start.clone().startOf("isoWeek").unix();this.end_normalized=this.end.unix()-this.end.clone().startOf("isoWeek").unix();this.dom_elements=[]}function d(a){return new c(moment(a.start+" "+f+" "+a.isoWeekday+" 1 1970","h:m a Z E WW YYYY"),a.duration)}var b="monday tuesday wednesday thursday friday saturday sunday".split(" "),
a=[e("Monday","12:00 PM",3),e("Monday","6:00 PM",2),e("Tuesday","12:00 PM",3),e("Wednesday","6:00 PM",2),e("Thursday","9:00 PM",2),e("Friday","12:00 PM",3),e("Saturday","3:00 PM",3),e("Sunday","11:00 AM",3)];c.prototype.toString=function(){var a=this.start.format("a"),b=this.end.format("a"),c=0<this.start.minutes()?["h:m","a"]:["h","a"],d=0<this.end.minutes()?["h:m","a"]:["h","a"];a===b&&c.pop();return this.start.format(c.join(" "))+" to "+this.end.format(d.join(" "))};c.prototype.is_live=function(a){return a>=
this.start_normalized&&a<=this.end_normalized};var f=w?"-0700":"-0800";window.export_internals&&(window.streamer_dst=w,window.visitor_timezone_offset=q,window.TimeSlot=e,window.make_stream=d);return a.map(d)}(),v=function(){function e(c,d){var b=c+" "+d;return 1<c?b+"s":b}return function(c,d){if(c===d)throw Error("get_countdown() called with invalid arguments");var b=d-c;0>b&&(b+=604800);var a=moment.duration(1E3*b),b=a.days(),f=a.hours(),g=a.minutes(),a=a.seconds(),l=[];b&&l.push(e(b,"day"));f&&
l.push(e(f,"hour"));g&&l.push(e(g,"minute"));a&&l.push(e(a,"second"));return l.join(", ")}}(),u=function(){function e(a,b){a.className&&0<a.className.match(new RegExp("(?:^|\\s)"+b+"(?!\\S)","g")).length&&(a.className=a.className.replace(new RegExp("(?:^|\\s)"+b+"(?!\\S)","g"),""))}for(var c=[],d=0,b={},a=0;a<g.length;a++)if(!(a in b)){b[a]=0;for(var f=g[a],h=[f],l=f.start.isoWeekday(),m=f.start.isoWeek(),n=f.start.year(),f=0;f<g.length;f++)f in b||g[f].start.isoWeekday()!=l||g[f].start.isoWeek()!=
m||g[f].start.year()!=n||(h.push(g[f]),b[f]=0);h.length>d&&(d=h.length);c.push(h)}for(f=document.querySelector("tr");f.children.length<c.length;)f.appendChild(document.createElement("th"));for(a=0;a<c.length;a++)f.children[a].textContent=c[a][0].start.format("dddd"),c[a][0].dom_elements.push(f.children[a]);for(b=document.querySelector("tbody");b.children.length<d;)b.appendChild(document.createElement("tr"));for(a=0;a<b.children.length;a++){for(d=b.children[a];d.children.length<c.length;)d.appendChild(document.createElement("td"));
0!==a&&(d.className="auxiliary-slots")}for(a=0;a<c.length;a++)for(f=0;f<c[a].length;f++)b.children[f].children[a].textContent=c[a][f].toString(),c[a][f].dom_elements.push(b.children[f].children[a]),1<=f&&(d=document.createElement("span"),d.className="same-line-slots",d.textContent=", "+c[a][f].toString(),b.children[0].children[a].appendChild(d));document.querySelector("small").textContent="All times are converted to your local time";var p=document.querySelector("h3"),k=document.querySelector("h1").children[0];
return function(a,b){a?(""===p.className&&(p.className+=" hidden"),e(k,"disguise"),k.textContent="Kate is live right now! Click to watch",k.href="http://www.twitch.tv/lovelymomo"):(e(p,"hidden"),""===k.className&&(k.className+=" disguise"),k.textContent=b,k.href="#")}}(),h=g[0],m=!0,t=-1;window.export_internals&&(window.get_countdown=v,window.streams=g,window.find_next_stream=r);n();setInterval(n,1E3)})();
