(function(){function v(b){function e(a,c,b){this.start=a.clone().zone(n);this.end=a.clone().zone(n);this.end.add("hours",c);this.duration=c;this.start_normalized=this.start.unix()-this.start.clone().startOf("isoWeek").unix();this.end_normalized=this.end.unix()-this.end.clone().startOf("isoWeek").unix();this.dom_elements=[];this.canceled=b}function f(a){var c=moment,b=a.time+" "+d+" ",f=a.weekday.toLowerCase(),f=w.indexOf(f);if(-1===f)throw Error("Invalid weekday name");return new e(c(b+(f+1)+" 1 1970",
"h:m a Z E WW YYYY"),a.duration,a.canceled)}e.prototype.toString=function(){var a=this.start.format("a"),c=this.end.format("a"),b=0<this.start.minutes()?["h:m","a"]:["h","a"],d=0<this.end.minutes()?["h:m","a"]:["h","a"];a===c&&b.pop();return this.start.format(b.join(" "))+" to "+this.end.format(d.join(" "))};e.prototype.is_live=function(a){return a>=this.start_normalized&&a<=this.end_normalized};var d=p?"-0700":"-0800";window.export_internals&&(window.streamer_dst=p,window.visitor_timezone_offset=
n,window.make_stream=f,window.Stream=e);return b.map(f).sort(function(a,c){return a.start_normalized-c.start_normalized})}function q(b,e){b=b.filter(function(b){return!b.canceled});var f;b.some(function(b){if(e>b.end_normalized)return!1;f=b;return!0});return f?f:b[0]}function x(b){for(var e=[],f=0,d={},a=0;a<b.length;a++)if(!(a in d)){d[a]=0;for(var c=b[a],g=[c],h=c.start.isoWeekday(),c=0;c<b.length;c++)c in d||b[c].start.isoWeekday()!==h||(g.push(b[c]),d[c]=0);g.length>f&&(f=g.length);e.push(g)}for(c=
document.querySelector("tr");c.children.length<e.length;)c.appendChild(document.createElement("th"));for(a=0;a<e.length;a++)c.children[a].textContent=e[a][0].start.format("dddd"),e[a][0].dom_elements.push(c.children[a]);for(b=document.querySelector("tbody");b.children.length<f;)b.appendChild(document.createElement("tr"));for(a=0;a<b.children.length;a++){for(c=b.children[a];c.children.length<e.length;)c.appendChild(document.createElement("td"));0!==a&&(c.className="auxiliary-slots")}for(a=0;a<e.length;a++)for(c=
0;c<e[a].length;c++)f=e[a][c],d=b.children[c].children[a],g=document.createElement("span"),g.textContent=e[a][c].toString(),f.canceled&&g.classList.add("canceled"),d.appendChild(g),f.dom_elements.push(b.children[c].children[a]),1<=c&&(d=document.createElement("span"),d.className="same-line-slots",d.textContent=", "+f.toString(),b.children[0].children[a].appendChild(d));var k=document.querySelector("h3"),l=document.querySelector("h1").children[0];return function(a,b){a?(k.classList.add("hidden"),l.classList.remove("disguise"),
l.textContent="Kate is live right now! Click to watch",l.href="http://www.twitch.tv/lovelymomo"):(k.classList.remove("hidden"),l.classList.add("disguise"),l.textContent=b,l.href="#")}}function r(b,e,f){for(var d=!1,a=0;a<b.length;a++)for(var c=0;c<b[a].dom_elements.length;c++)b[a].start.day()===e?(b[a].dom_elements[c].style.color="#333",d=!0):b[a].dom_elements[c].style.color="grey";if(!d)for(e=f.start.day(),a=0;a<b.length;a++)if(b[a].start.day()===e)for(c=0;c<b[a].dom_elements.length;c++)b[a].dom_elements[c].style.color=
"#333"}var p=moment().tz("america/vancouver").isDST(),n=(new Date).getTimezoneOffset(),w="monday tuesday wednesday thursday friday saturday sunday".split(" "),t=function(){function b(b,f){var d=b+" "+f;return 1<b?d+"s":d}return function(e,f){if(e===f)throw Error("get_countdown() called with invalid arguments");var d=f-e;0>d&&(d+=604800);var a=moment.duration(1E3*d),d=a.days(),c=a.hours(),g=a.minutes(),a=a.seconds(),h=[];d&&h.push(b(d,"day"));c&&h.push(b(c,"hour"));g&&h.push(b(g,"minute"));a&&h.push(b(a,
"second"));return h.join(", ")}}(),u=document.querySelector("#loading-message"),y=document.querySelector("#countdown"),m=new XMLHttpRequest;m.open("GET","/schedule.json");m.responseType="json";m.onload=function(){function b(){var g=moment(),h=g.unix(),k=h-g.clone().startOf("isoWeek").unix(),l=h-g.clone().startOf("day").unix(),h=g.day();h!==c&&r(e,h,d);c=h;g=g.hour()-Math.floor(l/3600);k+=3600*g;if(d.is_live(k))return a=!0,f(!0);if(a)return a=!1,d=q(e,k),r(e,h,d),b();a=!1;return f(!1,t(k,d.start_normalized))}
if(this.response){var e=v(this.response),f=x(e),d=e[0],a=!0,c=-1;window.export_internals&&(window.get_countdown=t,window.streams=e,window.find_next_stream=q,window.setTimeout(window.internal_exported,0));u.classList.add("hidden");y.classList.remove("hidden");b();setInterval(b,1E3)}else u.textContent="Schedule loading failed! If this problem persists, please contact the author"};m.send()})();
