(function(l){function q(a,d){a=a.filter(function(b){return!b.canceled});var b;a.some(function(a){if(d>a.end_normalized)return!1;b=a;return!0});return b?b:a[0]}function r(a,d){var b=document.createElement("span"),c=a.toString();d&&(c=", "+c,b.classList.add("same-line-slots"));b.textContent=c;a.canceled&&b.classList.add("canceled");return b}function t(a,d,b){var c=!1,e,f;for(e=0;e<a.length;e++)for(f=0;f<a[e].dom_elements.length;f++)a[e].start.day()===d?(a[e].dom_elements[f].style.color="#333",c=!0):
a[e].dom_elements[f].style.color="grey";if(!c)for(d=b.start.day(),e=0;e<a.length;e++)if(a[e].start.day()===d)for(f=0;f<a[e].dom_elements.length;f++)a[e].dom_elements[f].style.color="#333"}function p(){var a=moment(),d,b=a.unix();d=b-a.clone().startOf("isoWeek").unix();b-=a.clone().startOf("day").unix();b=a.hour()-Math.floor(b/3600);d+=3600*b;a=a.day();a!==u&&t(k,a,g);u=a;if(g.is_live(d))return m=!0,v(!0);if(m)return m=!1,g=q(k,d),t(k,a,g),p();m=!1;return v(!1,w(d,g.start_normalized))}var x=moment().tz("america/vancouver").isDST(),
y=(new Date).getTimezoneOffset(),z="monday tuesday wednesday thursday friday saturday sunday".split(" "),w=function(){function a(a,b){var c=a+" "+b;return 1<a?c+"s":c}return function(d,b){if(d===b)throw Error("get_countdown() called with invalid arguments");var c=b-d;0>c&&(c+=604800);var e=moment.duration(1E3*c),c=e.days(),f=e.hours(),n=e.minutes(),e=e.seconds(),h=[];c&&h.push(a(c,"day"));f&&h.push(a(f,"hour"));n&&h.push(a(n,"minute"));e&&h.push(a(e,"second"));return h.join(", ")}}(),v=function(){var a=
document.querySelector("h3"),d=document.querySelector("h1").children[0];return function(b,c){b?(a.classList.add("hidden"),d.classList.remove("disguise"),d.textContent="Kate is live right now! Click to watch",d.href="http://www.twitch.tv/lovelymomo"):(a.classList.remove("hidden"),d.classList.add("disguise"),d.textContent=c,d.href="#")}}(),A=document.querySelector("#countdown"),B=document.querySelector("#loading-message"),k=function(a){function d(a,b,c){this.start=a.clone().zone(y);this.end=this.start.clone();
this.end.add("hours",b);this.duration=b;this.start_normalized=this.start.unix()-this.start.clone().startOf("isoWeek").unix();this.end_normalized=this.end.unix()-this.end.clone().startOf("isoWeek").unix();this.dom_elements=[];this.canceled=c}function b(a){var b=moment,n=a.time+" "+c+" ",h=a.weekday.toLowerCase(),h=z.indexOf(h);if(-1===h)throw Error("Invalid weekday name");return new d(b(n+(h+1)+" 1 1970","h:m a Z E WW YYYY"),a.duration,a.canceled)}d.prototype.toString=function(){function a(b,c){var d=
b.hours();return 12===d?"Noon":0===d?"Beginning of day":b.format(c.join(" "))}var b=this.start,c=this.end,d=b.format("a"),k=c.format("a"),g=0<this.start.minutes()?["h:m","a"]:["h","a"],l=0<this.end.minutes()?["h:m","a"]:["h","a"];if(b.isoWeekday()!==c.isoWeekday())return a(b,g)+" for "+this.duration+" hours";d===k&&g.pop();return a(b,g)+" to "+a(c,l)};d.prototype.is_live=function(a){return a>=this.start_normalized&&a<=this.end_normalized};var c=x?"-0700":"-0800";window.export_internals&&(window.streamer_dst=
x,window.visitor_timezone_offset=y,window.make_stream=b,window.Stream=d);return a.map(b).sort(function(a,b){return a.start_normalized-b.start_normalized})}(l);l=function(a){var d,b,c=[],e={};for(d=0;d<a.length;d++)if(!(d in e)){e[d]=0;b=a[d];var f=[b],g=b.start.isoWeekday();for(b=0;b<a.length;b++)b in e||a[b].start.isoWeekday()!==g||(f.push(a[b]),e[b]=0);c.push(f)}return c}(k);var C=Math.max.apply(null,l.map(function(a){return a.length}));(function(a,d){var b,c,e=document.querySelector("tr");for(b=
0;b<a.length;b++){c=a[b][0];var f=document.createElement("th");f.textContent=c.start.format("dddd");c.dom_elements.push(f);e.appendChild(f)}e=document.querySelector("tbody");for(b=0;b<d;b++){c=a.length;for(f=document.createElement("tr");f.children.length<c;)f.appendChild(document.createElement("td"));c=f;0!==b&&(c.className="auxiliary-slots");e.appendChild(c)}for(b=0;b<a.length;b++)for(c=0;c<a[b].length;c++){var f=a[b][c],g=e.children[c].children[b];g.appendChild(r(f));f.dom_elements.push(g);1<=c&&
e.children[0].children[b].appendChild(r(f,!0))}})(l,C);var g=k[0],m=!0,u=-1;window.export_internals&&(window.get_countdown=w,window.streams=k,window.find_next_stream=q,window.setTimeout(window.internal_exported,0));B.classList.add("hidden");A.classList.remove("hidden");p();setInterval(p,1E3)})([{weekday:"Monday",time:"6:00 PM",duration:2,canceled:!1},{weekday:"Wednesday",time:"5:00 PM",duration:2,canceled:!1},{weekday:"Thursday",time:"9:00 PM",duration:2,canceled:!1},{weekday:"Saturday",time:"3:00 PM",
duration:2,canceled:!1},{weekday:"Sunday",time:"4:00 PM",duration:2,canceled:!1}]);
